apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-demo-v2
  labels:
    app: rollouts-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:green
          ports:
            - containerPort: 8080
