apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:blue
          ports:
            - containerPort: 8080
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 10s }
        - analysis:
            templates:
              - templateName: success-rate-prometheus
            args: []
        - setWeight: 60
        - pause: { duration: 10s }
        - analysis:
            templates:
              - templateName: success-rate-prometheus

# You can swap success-rate-prometheus with rollout-validation-job for Job-based testing.
