apiVersion: batch/v1
kind: Job
metadata:
  name: rollout-job-failure
spec:
  template:
    spec:
      containers:
        - name: test
          image: busybox
          command: ["sh", "-c", "echo Something went wrong && exit 1"]
      restartPolicy: Never
